### ISSUE TITLE
fish 3.0.1?

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5520]
I'm asking for opinions on whether to put out a 3.0.1 to fix showstopping bugs following 3.0.0, and what to include. I would be aiming to get it out this month. Otherwise they will have to wait for 3.1.0, which I've got planned for March or so.

Candidates include:
- [x] #5449 (regression)
- [x] #5426 (build failure on Cygwin)
- [x] #5438 (regression)
- [x] #5519 (regression, unfixed as of this writing)
- [x] #5453 (possibly - memory corruption, hit in the tests, could conceivably be hit in production)
- [x] #5458 (possibly - failure on OpenIndiana)
- [x] #5479 (memory corruption segfault, hit in the tests, could conceivably be hit in production)

**Comment by mqudsi** [comment]
I think the OpenIndiana folks are doing a fine job incorporating patches and updates post 3.0, so #5458 isn't very important. The others all sound worth including.

**Comment by cdluminate** [comment]
I (Debian developer maintaining fish) hereby second the request for the 3.0.1 release. We are reaching the freezing stage of the next stable release (aka. Debian Buster) [1]. And the timing of 3.1.0 release sounds too late for Debian Buster. So I think releasing 3.0.1 would make great sense.

[1] https://release.debian.org/

**Comment by faho** [comment]
I'm all for doing a bugfix release!

The question is always how big we want it to be?

I would say anything from https://github.com/fish-shell/fish-shell/issues?utf8=%E2%9C%93&
q=is%3Aissue+is%3Aclosed+milestone%3A%22fish+3.1.0%22+ is a candidate here.

Some things I think should be included:

- #5481 is a regression and an easy fix

- #5447, at least https://github.com/fish-shell/fish-shell/commit/a7998c4829a80269bcd6af941812e35c86bf49e2 is a performance regression fixed by removing an assert.

And some maybes:

- #5476, given that it's been reported twice. It's more of a matter of taste, though.

- #5513 would be nice to include, if we can get it fixed in a timely manner

- #5456 would be nice to have, if we can come up with an answer for it. It's slightly larger, though.

**Comment by floam** [comment]
Yes, I think we should, there are a few real stinkers that would be nice to get out of the way so we can focus on having time to do a nice 3.1.

**Comment by mqudsi** [comment]
I personally view #5513 as worthy of a 3.0.1 all on its own, but maybe that's just me.

**Comment by drupol** [comment]
Please fix the Freebsd issue.

**Comment by ridiculousfish** [comment]
I've got two weeks free, I can definitely do this.

**Comment by ridiculousfish** [comment]
master has diverged too far so 3.0.1 should be based on 3.0.0. I've added an Integration_3.0.1 branch to origin, let's fix the 3.0.1 issues in master, and cherry-pick into Integration_3.0.1.

**Comment by ridiculousfish** [comment]
Milestone is complete, let's do it!

**Comment by zanchey** [comment]
Awesome - well done. I should have time to roll the release in the next week or so (perhaps even tonight).

**Comment by ridiculousfish** [comment]
Thanks everyone for the hard and timely work here!
